# Tasks to run before running rules
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache
      tags: always
      apt:
        update_cache: true
        # upgrade: yes
      changed_when: false

# Run roles
- hosts: all
  tags: base
  become: true
  roles:
    - base

- hosts: workstation
  tags: workstation
  become: true
  roles:
    - workstation

- hosts: server
  tags: server
  become: true
  roles:
    - server

# Cleanup
- hosts: all
  become: true
  tasks:
    - name: cleanup package cache
      tags: always
      apt:
        autoclean: true
      changed_when: false

    - name: autoremove orphan packages
      tags: always
      apt:
        autoremove: true
        purge: true

    # - name: Reboot when packages were updated
    #   reboot:
    #   when: yum_update_status.changed
