- name: software | firefox | install package
  tags: packages,firefox,workstation-packages
  become_user: venkivijay
  package:
    name: firefox
    state: present
  become: true
  become_method: sudo
  when: firefox is defined and firefox
