- name: software | telegram | install package
  tags: packages,telegram,flatpak,workstation-packages
  become_user: venkivijay
  flatpak:
    name: org.telegram.desktop
    method: user
    state: present
  when: telegram is defined and telegram
