# Load distro-specific variables
- name: workstation | include vars
  include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
    ## User configs
    - import_tasks: users/venkivijay.yml

    ## system setup
    - import_tasks: system_setup.yml

    ## powerline fonts
    - import_tasks: powerline_fonts.yml

    ## gnome specific
    - block:
        - import_tasks: gnome/appearance.yml
        - import_tasks: gnome/peripherals.yml
        - import_tasks: gnome/terminal.yml
      when: gnome is defined and gnome

    ## install software
    - import_tasks: softwares/cheese.yml
    - import_tasks: softwares/firefox.yml
    - import_tasks: softwares/gimp.yml
    - import_tasks: softwares/google_chrome.yml
    - import_tasks: softwares/minecraft.yml
    - import_tasks: softwares/postman.yml
    - import_tasks: softwares/steam.yml
    - import_tasks: softwares/telegram.yml
    - import_tasks: softwares/terminator.yml
    - import_tasks: softwares/transmission.yml
    - import_tasks: softwares/virtualbox.yml

  rescue:
    - name: workstation | rescue
      set_fact: task_failed=true
