- name: ansible setup | ensure ansible is the latest version
  tags: ansible,ansible-setup
  package:
    name: ansible
    state: present

- name: ansible setup | install required packages
  tags: ansible,ansible-setup,packages
  package:
    name:
      - "{{ python_psutil_package }}"
    state: present

- name: ansible setup | install acl package
  tags: ansible,ansible-setup,packages
  package:
    name: acl
    state: present
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

- name: ansible setup | create ansible log file
  tags: ansible,ansible-setup
  file:
    path: /var/log/ansible.log
    owner: venkivijay
    group: venkivijay
    mode: 0664
    state: touch
  changed_when: false

- name: ansible setup | add logrotate config for ansible log file
  tags: ansible-setup
  copy:
    src: files/ansible_setup/logrotate
    dest: /etc/logrotate.d/ansible
    owner: root
    group: root
    mode: 0644

- name: ansible setup | remove default ansible directory (/etc/ansible) from host
  tags: ansible,ansible-setup
  file:
    path: /etc/ansible
    state: absent

- name: ansible setup | generate provision script from template
  tags: ansible,ansible-setup,scripts
  template:
    src: provision.sh.j2
    dest: /usr/local/bin/provision
    owner: root
    group: root
    mode: 0755

- name: ansible setup | cron | schedule ansible provision
  tags: cron,system setup
  cron:
    name: ansible-provision
    hour: "{{ ansible_provision_hour | default('*') }}"
    minute: "{{ ansible_cron_minute | default('*/30') }}"
    job: /usr/local/bin/provision
    user: venkivijay

- name: ansible setup | cron | schedule ansible cleanup at boot
  tags: cron,system setup
  cron:
    name: ansible-cleanup
    special_time: reboot
    job: /bin/rm -rf /home/venkivijay/.ansible
    user: venkivijay
