- name: base | include vars
  include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
    # Install Prerequisite packages
    - import_tasks: softwares/prerequisite_packages.yml

    # Setup system
    - import_tasks: system_setup.yml

    # Create and setup users
    - import_tasks: users/venkivijay.yml
    - import_tasks: users/root.yml

    # Install Node and NVM
    - import_tasks: softwares/node_setup.yml

    # Set up the ansible environment
    - import_tasks: ansible_setup.yml

  rescue:
    - name: base | rescue
      set_fact: task_failed=true
