- name: system software | nodejs | install
  become: true
  package:
    state: present
    name:
      - nodejs
      - npm
  tags: software,nodejs

- name: system software | n | install
  npm:
    name: n
    global: true
  ignore_errors: "{{ ansible_check_mode }}"
  tags: software,nodejs,n

- name: system software | node 14 | setup
  command: n 14
  register: nvmstat
  changed_when: nvmstat.rc != 0
  ignore_errors: "{{ ansible_check_mode }}"
  tags: software,nodejs,nvm
