- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - curl
      - lm-sensors
      - lsof
      - neofetch
      - rsync
      - wget
      - whois
      - zsh
