- name: system setup | prerequisite | install packages
  tags: packages,system,settings
  package:
    state: present
    name:
      - curl
      - lsof
      - rsync
      - wget
      - whois
      - zsh
      - git
